import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file if it exists
load_dotenv()

# --------------------------------------------------
# 1. Path Configuration
# --------------------------------------------------
# Since config.py is in the root directory, .parent gives us the root path.
BASE_DIR = Path(__file__).resolve().parent

# Define the main data directory
DATA_DIR = BASE_DIR / "data"

# Define the subdirectories for raw and processed data
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

# Create these directories if they don't exist yet
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------
# 2. File Paths Constants
# --------------------------------------------------
# Input files (To be downloaded)
RAW_LOAN_DATA_FILE = RAW_DATA_DIR / "lending_club_loan.csv"

# --- Census Data Configuration ---
# Pointing to the specific download folder found in your directory listing
CENSUS_RAW_DIR = RAW_DATA_DIR / 'productDownload_2026-02-17T231823'

CENSUS_FILE_2022 = CENSUS_RAW_DIR / 'ACSST5Y2022.S2503-Data.csv'
CENSUS_FILE_2023 = CENSUS_RAW_DIR / 'ACSST5Y2023.S2503-Data.csv'
CENSUS_FILE_2024 = CENSUS_RAW_DIR / 'ACSST5Y2024.S2503-Data.csv'

# Output files (Generated by ETL process)
PROCESSED_LOAN_DATA_FILE = PROCESSED_DATA_DIR / 'loans_cleaned.parquet'
# Note: We use .parquet for processed data because it's faster and smaller than .csv

# Output for processed Census features (Updated to .parquet)
PROCESSED_CENSUS_FILE = PROCESSED_DATA_DIR / 'census_economic_features.parquet'

# Database Export File (Optional backup)
DB_EXPORT_FILE = PROCESSED_DATA_DIR / "database_export.csv"

# --------------------------------------------------
# 3. Database Configuration (PostgreSQL)
# --------------------------------------------------
# Please match these settings to your local PostgreSQL instance
DB_CONFIG = {
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", "YOUR_OWN_PASSWORD"),
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5432"),
    "database": os.getenv("DB_NAME", "credit_risk_db")
}

# Construct the SQLAlchemy Database URL
DB_URL = (
    f"postgresql+psycopg2://{DB_CONFIG['user']}:{DB_CONFIG['password']}"
    f"@{DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['database']}"
)
